version: '3.8'

services:
  app:
    build: projeto
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_ENDPOINT=redis:6379

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
